/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.15";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/home/lwang/dce/build/etc/wgetrc\" -DLOCALEDIR=\"/home/lwang/dce/build/share/locale\" -I. -I../lib -I../lib -fPIC -g";
const char *link_string = "gcc -fPIC -g -pie -rdynamic -lpcre ../lib/libgnu.a";
