# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('tinyxml2-example', ['tinyxml2'])
    obj.source = 'tinyxml2-example.cc'

